color = input("Enter the color:")
plural_noun = input("Enter the pural noun:")
celebrity = input("Enter the celebrity:")
print("Roses are " + color)
print(plural_noun + " are blue")
print("I love " + celebrity)